### ISSUE TITLE
pref_headers cannot be resolved or is not a field

### ISSUE THREAD

**Issue by Ibochkarev** [saik0/UnifiedPreference#14]
Adding to the project library created a folder xml for a file called hml. In the activity of adding the file and get an error

``` java
package ru.test.android.enviroment;

import android.R;
import android.content.Context;
import android.os.Bundle;

import net.saik0.android.unifiedpreference.UnifiedPreferenceFragment;
import net.saik0.android.unifiedpreference.UnifiedSherlockPreferenceActivity;

public class PreferenceActivity extends UnifiedSherlockPreferenceActivity {

    @Override public void onCreate(Bundle savedInstanceState) {
        // Set header resource MUST BE CALLED BEFORE super.onCreate
                setHeaderRes(R.xml.pref_headers);
                // Set desired preference file and mode (optional)
    }

    public static class GeneralPreferenceFragment extends UnifiedPreferenceFragment {}
}
```

Error:
pref_headers cannot be resolved or is not a field   PreferenceActivity.java /SplashActivity/src/ru/test/android/enviroment  line 14 Java Problem

**Comment by jromero** [comment]
You are importing android.R instead of `ru.test.android.enviroment.R` class.

Such that...
pref_headers should be a file on YOUR project.
It should be located under <project>/res/xml/pref_headers.xml

For contents see: 
https://github.com/saik0/UnifiedPreference/blob/master/demo/res/xml/pref_headers.xml
and:
https://github.com/saik0/UnifiedPreference/blob/master/demo/res/xml/pref_general.xml
